controller_manager:
  ros__parameters:
    update_rate: 500 # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

joint_group_position_controller:
  ros__parameters:
    joints:
      - body_drawer1
      - body_drawer2
      - body_drawer3
      - body_drawer4
      - body_drawer5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    # Add velocity and acceleration constraints
    max_velocity: 1.0 # rad/s
    max_acceleration: 2.0 # rad/s^2

    # PID gains for each joint
    gains:
      body_drawer1: { p: 10.0, i: 10.0, d: 1.0 }
      body_drawer2: { p: 10.0, i: 10.0, d: 1.0 }
      body_drawer3: { p: 10.0, i: 10.0, d: 1.0 }
      body_drawer4: { p: 10.0, i: 10.0, d: 1.0 }
      body_drawer5: { p: 10.0, i: 10.0, d: 1.0 }
